### PR TITLE
feat: v1 mud setup

### PR DESCRIPTION
**Pull request by junaama**

### CODE REVIEW

**Comment by junaama** [comment]
Entity **Character (v1)** has components `Identity`, `Element`, `Asset`, `Effect`, `Power`, `Rank`, `Position`, `OwnedBy`

**Review by marvinmarnold — APPROVED** [review]
Great start!

**Comment by Oba-One** [comment]
> Entity **Character (v1)** has components `Identity`, `Element`, `Asset`, `Effect`, `Power`, `Rank`, `Position`, `OwnedBy`

Awesome! Was thinking we will also need energy to account for the energy needed to play a character.

**Comment by junaama** [comment]
# V1
## Contracts
### Entity
- Character
### Components
- Asset
- Identity
- OwnedBy
- Position
### System
- Init
## Client
- Basic rendering of characters on the page

**Pull request merged**
